# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ja:
  languageCode: ja-jp
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en
  menu:
    main:
    - name: Home
      url: '#about'
      weight: 10
    - name: Research
      url: '#research'
      weight: 20
    - name: Teaching
      url: '#teaching'
      weight: 30
    - name: Contact
      url: '#contact'
      weight: 40


# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
