# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: トップ
    url: '#about'
    weight: 10
  - name: 研究関連
    url: '/research'
    weight: 20
  - name: 教育活動
    url: '/teaching'
    weight: 30
  - name: 雑記
    url: '/post'
    weight: 40
  - name: お問合せ
    url: '#contact'
    weight: 60
    
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
