---
pagetitle: "Research | KAKINUMA Hideki"
---

# 研究 | Research {.tabset}

## 日本語
<h4>研究関心 / プロジェクト</h4>
+ タレントマネジメント
    + タレントマネジメント論の理論的研究
    + タレントマネジメント関連文献の計量書誌学的分析
    + 日本企業におけるタレントマネジメント実践の事例分析
+ サービス人的資源管理
    + サービス組織における人材開発
    + 宿泊産業における人材定着

<h4 class="mb">主な書籍</h4>
+ 柿沼英樹 (2022)「人材育成とキャリア」西村孝史・島貫智行・西岡由美編著『1からの人的資源管理』(pp.105-119). 碩学舎.
+ 柿沼英樹・土屋裕介 (2020)『タレントマネジメント入門：個を活かす人事戦略と仕組みづくり』ProFuture.

<h4 class="mb">主な論文</h4>
+ 柿沼英樹 (2021)「2000年代以降の人的資源管理研究におけるタレントマネジメントの位置づけ－計量書誌学的手法による探索的分析－」『流通科学大学論集 流通・経営編』33, 53-71.
+ 柿沼英樹 (2019)『タレントマネジメント論の理論的展開とその日本型人事管理への含意』京都大学大学院経済学研究科博士学位申請論文.
+ 柿沼英樹 (2018)「タレントマネジメント論の計量書誌学的分析」『環太平洋大学研究紀要』*13*, 89-98.
+ 柿沼英樹 (2015)「企業におけるジャストインタイムの人材配置の管理手法の意義－人的資源管理論でのタレントマネジメント論の展開」『経済論叢（京都大学）』*189* (2), 49-60.（査読あり）
+ Kakinuma, H. (2015). How companies can attract the talented Vietnamese graduates? An experimental-designed investigation. *International Journal of Business and Management*, *10* (2), 31-40. (Referred)
 
 
より詳細な業績情報は、Researchmapをご参照ください。  
http://researchmap.jp/hkakinuma



## English

<h4>Research interests / projects</h4>
+ Talent management
    + Theoretical development of talent management
    + Bibliometric analysis of talent management studies
    + Talent management in Japanese firms
+ Human resource management in the service sector
    + Human resource development in service industries
    + Turnover / Retention in the lodging industry

<h4 class="mb">Published paper (In English)</h4>
+ Kakinuma, H. (2015). How companies can attract the talented Vietnamese graduates? An experimental-designed investigation. *International Journal of Business and Management*, *10* (2), 31-40. (Referred)

<h4 class="mb">International conferences that have paper presented [Alphabetical]</h4>
+ APacCHRIE Conference [2018]
+ EIASM Workshop on Strategic Human Resource Management [2012]
+ EIASM Workshop on Talent Management [2012, 2013]
+ IFSAM [2015]
+ Management Theory and Practice Conference [2016]
+ Paris colloquium on Human Resource Management in Asia: Distinctiveness of Asian Human Resource Management? [2015]

Please check the "Researchmap" linked below, if detailed information is needed.  
https://researchmap.jp/hkakinuma/?lang=english  
